import type { NextPage } from 'next'
import dynamic from 'next/dynamic'
import Head from 'next/head'
import styled from 'styled-components';

const Container = styled.div`
  height: 100%;
`;
const Main = styled.main`
  height: 100%;
`;


const Home: NextPage = () => {
  const Map = dynamic(
    () => import('./Map'),
    { ssr: false }
  )
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Map />
      </Main>
    </Container>
  )
}

export default Home
